spring:
  profiles:
    active: set1
---
spring:
  config:
    activate:
      on-profile: set1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://sopt-deploy-database.c5sk66kiular.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: deploy
    password: deploysopt
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: set2
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://sopt-deploy-database.c5sk66kiular.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: deploy
    password: deploysopt
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  port: 8082
